# This workflow publishes packages to Maven Central using JReleaser
# For more information see: https://jreleaser.org/guide/latest/examples/maven/maven-central.html

name: Publish to Maven Central

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build and publish to Maven Central - All modules
        if: contains(github.event.release.tag_name, '-all')
        run: |
          ./gradlew build -x test
          ./gradlew publishLibraryPublicationToOSSRHRepository :apache-tomcat:publishLibraryPublicationToOSSRHRepository jreleaserFullRelease -Djreleaser.select.current.project
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish to Maven Central - Baradum only
        if: contains(github.event.release.tag_name, '-baradum')
        run: |
          ./gradlew build -x test
          ./gradlew publishLibraryPublicationToOSSRHRepository jreleaserFullRelease -Djreleaser.select.current.project
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish to Maven Central - Apache Tomcat only
        if: contains(github.event.release.tag_name, '-apache-tomcat')
        run: |
          ./gradlew build -x test
          ./gradlew :apache-tomcat:publishLibraryPublicationToOSSRHRepository :apache-tomcat:jreleaserFullRelease -Djreleaser.select.current.project
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-logs
          path: |
            build/jreleaser/trace.log
            build/jreleaser/output.properties