# This workflow publishes packages to Maven Central using JReleaser
# For more information see: https://jreleaser.org/guide/latest/examples/maven/maven-central.html

name: Publish to Maven Central

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup GPG
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format SHORT
          mkdir -p $HOME/.gnupg
          chmod 700 $HOME/.gnupg
          gpg --batch --export-secret-keys --pinentry-mode=loopback --passphrase "${{ secrets.GPG_SECRET_KEY_PASSWORD }}" -o $HOME/.gnupg/secring.gpg

      - name: Build and publish to Maven Central - All modules
        if: contains(github.event.release.tag_name, '-all')
        run: |
          ./gradlew build -x test
          ./gradlew -Psigning.keyId=${{ secrets.GPG_SHORT_KEY }} -Psigning.password=${{ secrets.GPG_SECRET_KEY_PASSWORD }} -Psigning.secretKeyRingFile=$HOME/.gnupg/secring.gpg publishLibraryPublicationToOSSRHRepository :apache-tomcat:publishLibraryPublicationToOSSRHRepository
          ./gradlew jreleaserDeploy
          ./gradlew :apache-tomcat:jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish to Maven Central - Baradum only
        if: contains(github.event.release.tag_name, '-baradum')
        run: |
          ./gradlew build -x test
          ./gradlew -Psigning.keyId=${{ secrets.GPG_SHORT_KEY }} -Psigning.password=${{ secrets.GPG_SECRET_KEY_PASSWORD }} -Psigning.secretKeyRingFile=$HOME/.gnupg/secring.gpg publishLibraryPublicationToOSSRHRepository
          ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish to Maven Central - Apache Tomcat only
        if: contains(github.event.release.tag_name, '-apache-tomcat')
        run: |
          ./gradlew build -x test
          ./gradlew -Psigning.keyId=${{ secrets.GPG_SHORT_KEY }} -Psigning.password=${{ secrets.GPG_SECRET_KEY_PASSWORD }} -Psigning.secretKeyRingFile=$HOME/.gnupg/secring.gpg :apache-tomcat:publishLibraryPublicationToOSSRHRepository
          ./gradlew :apache-tomcat:jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-logs
          path: |
            build/jreleaser/trace.log
            build/jreleaser/output.properties
            apache-tomcat/build/jreleaser/trace.log
            apache-tomcat/build/jreleaser/output.properties